name: DEV - CI Trigger

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Eslint check
        run: |
          npm install
          npm run lint

      - name: Docker build
        run: docker build -t ani:latest .
