name: Push Develop Trigger

on:
  push:
    branches: [learn]

  workflow_dispatch:

jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: npm install
        uses: actions/checkout@v2
        with:
          args: install

      - name: docker login registry.teav4.com
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login registry.teav4.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker build
        run: docker build -t ani:latest .
      - name: Tag the Docker image
        run: docker tag ani:latest registry.teav4.com/ani:latest
      - name: docker push
        run: docker push registry.teav4.com/ani:latest
